### ISSUE TITLE
anko-common artifact is deprecated and  renamed to anko-commons

### ISSUE THREAD

**Issue by LaysDragon** [BennyWang/KBinding#14]
The dependency of anko-common is deprecated and renamed to anko-commons at version 0.10
This cause the Gradle can't solve the dependency conflict problem with newer version of anko-commons.
I had to manually to exclude the anko-common from dependency as a  workaround.
``` gradle
configurations {
    //手動排除一個舊版模組，因為差了一個字所以沒辦法被正確處理版本衝突
    all*.exclude group: 'org.jetbrains.anko', module: 'anko-common'
}
dependencies {
...
 compile "org.jetbrains.anko:anko-commons:$anko_version"
...
}
```

**Comment by BennyWang** [comment]
@laysdra7265 fixed, version update to 0.2.4
